version: "3.8"
services:
  booksales:
    build:
      context: ./
      dockerfile: booksales.dockerfile
    command: "python main.py"
    volumes:
      - ./:/code
    ports:
      - "9090:9090"
    depends_on:
      - "db"
    environment:
      "DB_NAME": "booksales"
      "DB_USER": "booksales"
      "DB_PWD": "booksales"
      "DB_PORT": "5432"
      "DB_HOST": "db"
    container_name: "booksales"
    stdin_open: true
    tty: true
  db:
    image: postgres:13.2-alpine
    ports:
      - "5432:5432"
    environment:
      "POSTGRES_DB": "booksales"
      "POSTGRES_USER": "booksales"
      "POSTGRES_PASSWORD": "booksales"
    container_name: "booksales_db"
