"""create_sale

Revision ID: 35232a2be0cc
Revises: f174160e7419
Create Date: 2021-03-21 21:23:50.232064

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '35232a2be0cc'
down_revision = 'f174160e7419'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sale_sale',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer_customer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sale_sale')
    # ### end Alembic commands ###
