"""add unique constraints to book

Revision ID: 492d9259c85b
Revises: f3c6f75d2ddb
Create Date: 2021-03-22 01:23:38.671893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '492d9259c85b'
down_revision = 'f3c6f75d2ddb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'book_book', ['ISBN'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'book_book', type_='unique')
    # ### end Alembic commands ###
