"""change nullables

Revision ID: 8b7e0f3cc210
Revises: b784aa53b4c6
Create Date: 2021-03-21 16:57:04.180851

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = '8b7e0f3cc210'
down_revision = 'b784aa53b4c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('book_book', 'ISBN',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('book_book', 'author',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
    op.alter_column('book_book', 'language',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
    op.alter_column('book_book', 'price',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('book_book', 'title',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
    op.alter_column('book_book', 'year',
               existing_type=sa.SMALLINT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('book_book', 'year',
               existing_type=sa.SMALLINT(),
               nullable=True)
    op.alter_column('book_book', 'title',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
    op.alter_column('book_book', 'price',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('book_book', 'language',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
    op.alter_column('book_book', 'author',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
    op.alter_column('book_book', 'ISBN',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###
