"""create_sale_books_relationship

Revision ID: a892f12aece6
Revises: 35232a2be0cc
Create Date: 2021-03-21 21:37:39.075507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a892f12aece6'
down_revision = '35232a2be0cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sale_book_sale',
    sa.Column('sale_id', sa.Integer(), nullable=True),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['book_book.id'], ),
    sa.ForeignKeyConstraint(['sale_id'], ['sale_sale.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sale_book_sale')
    # ### end Alembic commands ###
