"""add_non_nullable_to_sale_book_relationship

Revision ID: b15f4151276d
Revises: a892f12aece6
Create Date: 2021-03-21 22:01:36.942499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b15f4151276d'
down_revision = 'a892f12aece6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sale_book_sale', 'book_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('sale_book_sale', 'sale_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sale_book_sale', 'sale_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('sale_book_sale', 'book_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
